name: Enable Auto‑Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
